### ISSUE TITLE
Needs more tests

### ISSUE THREAD

**Issue by asomers** [KhaledEmaraDev/xfuse#32]
The current test suite has very poor coverage.  Before it will be production ready, this project needs much better coverage.  This bug will track progress as the test suite is improved:

- [x] readdir returns "." and ".." entries (#40)
- [x] lookup works on "." and ".." entries (#40)
- [x] lookup
- [x] Read data from dense files that use XFS_DINODE_FMT_EXTENTS (#67)
- [x] Read data from dense files that use XFS_DINODE_FMT_BTREE (#67)
- [x] Read data from sparse files (#91)
- [ ] Read data from reflinks
- [ ] lseek with SEEK_HOLE/SEEK_DATA
- [ ] lseek with SEEK_HOLE should return ENXIO when the offset points past EoF
- [x] stat can read all file metadata (#61)
- [x] Timestamps from before the Epoch are reported correctly. (#64)
- [x] readlink on a short form symlink (#54)
- [x] readlink on an extent symlink (#54)
- [x] stat on a short form symlink (#62)
- [x] stat on an extent symlink (#62)
- [x] stat works for fifos, sockets, blk, and chr devices. (#64)
- [x] hardlinks work.  stat should return the same metadata for each and the link count should be correct.  lookup via both paths should return the same ino. (#62)
- [x] A XFS_DINODE_FMT_LOCAL file's extended attributes can be listed. (#47)
- [x] A XFS_DINODE_FMT_EXTENTS file's extended attributes can be listed.  (#47)
- [ ] A file's extended attributes can be listed if they are stored in a BTree (XFS_DA3_NODE_MAGIC)
- [ ] A XFS_DINODE_FMT_BTREE file's extended attributes can be listed.
- [ ] Extended attributes that use short form and XFS_DINODE_FMT_LOCAL can be read.
- [ ] Extended attributes that use leaf and XFS_DINODE_FMT_EXTENTS can be read.
- [ ] Extended attributes that use node and XFS_DINODE_FMT_EXTENTS can be read.
- [ ] Extended attributes that use btrees and XFS_DINODE_FMT_BTREE can be read.
- [ ] Extended attributes both version 1 and 2 can be read.
- [x] Attempt to get a non-existent extended attribute fails gracefully. (#65)
- [x] statfs and statvfs return reasonable values for all fields. (#63)

**Comment by asomers** [comment]
Since this list is mostly complete, I'm going to close the issue.  The remaining items are tracked as separate issues: #106 #113  and #114 .
